Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 300
Metrics/MethodLength:
  Max: 20
Style/Encoding: 
  Enabled: false
Metrics/ClassLength:
  Max: 1000
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20